name: Spell Check .md
on: push

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    name: Spellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Spellcheck
        uses: tbroadley/spellchecker-cli-action@v1
        with:
          files: "docs/**/*.md **/*.md *.md"
          quiet: true
          noSuggestions: true
          dictionaries: ".github/dictionary.txt"
          reports: "report.json"
          plugins: "spell repeated-words syntax-mentions syntax-urls frontmatter"
      - name: Report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v5
        with:
          name: report
          path: report.json
