on:
  push:
    branches:
      - develop
    paths:
      - 'tweets/**'
      - '**twitter-preview.yml'
      - '**twitter-tweet.yml'

name: Twitter, together!
jobs:
  tweet:
    name: Tweet
    runs-on: ubuntu-latest
    environment:
      name: twitter
      url: https://twitter.com/ASFHyP3
    steps:
      - uses: actions/checkout@v2

      - name: Tweet
        uses: gr2m/twitter-together@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
